### ISSUE TITLE
Dirty Dentry Event of constantly updated Inode is not written back after Kernel Logrotate

### ISSUE THREAD

**Issue by juergenc** [schoebel/filemon2#4]
### Release
```sh
cat /proc/version 
Linux version 4.4.185-icpu-025-g6ffde592baba (root@mini-buildd-3) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #2 SMP Wed Jul 17 07:24:14 UTC 2019
```

### Steps to Reproduce (file touch)
1. Have a monitored Filemonitor II partition in place, with standard values (no extra *.conf files in `.filemon2/` directory)
1. `cd fm2/partition/root`
1. Touch a file on FM2-partition-root every two seconds: `while sleep 2; do touch xy; done`
1. We will find - of course - an event entry in the currently opened kernel event log file:
```sh
less +F .filemon2/eventlog-000003348.log
event_stamp now_stamp events_new events_cumul repeated i_ino i_generation pid path
## CONT_EPOCH=1568970326.921233648
## MASK=0x7087e0
# MOUNT            1568970326.921233648 1579519192.719096187
1579519497.906685027 1579519497.906685027 300020 300020 3 19113 1285332784 283 /xy
# LOGROT_BEGIN     1568970326.921233648 1579519798.905972816
```
1. Right before the next "natural" (not enforced by the user in any way) logrotate, it is expected the _dirty_ dentry cache with not yet committed events to the kernel event log file, are flushed to it, but this is not the case. The created kernel event log file with the next higher consecutive log index number does not show up any new event of the touched file:
```sh
less +F .filemon2/eventlog-000003349.log
vent_stamp now_stamp events_new events_cumul repeated i_ino i_generation pid path
## CONT_EPOCH=1568970326.921233648
## MASK=0x7087e0
# LOGROT_END       1568970326.921233648 1579519798.905972816
# LOGROT_BEGIN     1568970326.921233648 1579520405.356735672
```
1. If we stop the continuous running process `while sleep 2; do touch xy; done` and wait for a minute (default dentry dirty dentry timeout), the event is written back to the currently opened kernel event log file as expected:
```sh
event_stamp now_stamp events_new events_cumul repeated i_ino i_generation pid path
## CONT_EPOCH=1568970326.921233648
## MASK=0x7087e0
# LOGROT_END       1568970326.921233648 1579520405.356735672
1579520604.884136009 1579520665.568824133 300000 8000000000300020 1104 19113 1285332784 283 /xy
# LOGROT_BEGIN     1568970326.921233648 1579521011.903610894
```
### Steps to Reproduce (file append)
`.filemon2/` directory)
1. `cd fm2/partition/root`
1. file `xy` in which append data already exists
1. Append to a file on FM2-partition-root every two seconds: `while sleep 2; do echo $(date) >> xy; done`
1. We will find - of course - an event entry in the currently opened kernel event log file:
```sh
event_stamp now_stamp events_new events_cumul repeated i_ino i_generation pid path
## CONT_EPOCH=1568970326.921233648
## MASK=0x7087e0
# LOGROT_END       1568970326.921233648 1579521618.526622215
1579522023.802072231 1579522023.802072231 8000 8000 1 19113 1285332784 283 /xy
# LOGROT_BEGIN     1568970326.921233648 1579522225.009662735
```
1. Same as in the first test, after "natural" logrotate (not enforced by the user in any way), there is no event of the still continuously appended file `xy`:
```sh
event_stamp now_stamp events_new events_cumul repeated i_ino i_generation pid path
## CONT_EPOCH=1568970326.921233648
## MASK=0x7087e0
# LOGROT_END       1568970326.921233648 1579522225.009662735
```
1. If we stop the continuous running process `while sleep 2; do echo $(date) >> xy; done` and wait for a minute (default dentry dirty dentry timeout), the event is written back to the currently opened kernel event log file as expected:
```sh
event_stamp now_stamp events_new events_cumul repeated i_ino i_generation pid path
## CONT_EPOCH=1568970326.921233648
## MASK=0x7087e0
# LOGROT_END       1568970326.921233648 1579522225.009662735
1579522744.901950118 1579522805.318634973 8000 8000000000008000 353 19113 1285332784 283 /xy
# LOGROT_BEGIN     1568970326.921233648 1579522831.320651392
```

### Enforcing by creating `.filemon2/extra-logrot-fm2.cmd`
1. Have a monitored Filemonitor II partition in place, with standard values (no extra *.conf files in `.filemon2/` directory)
1. `cd fm2/partition/root`
1. Touch a file on FM2-partition-root every two seconds: `while sleep 2; do touch xy; done`
1. We will find - of course - an event entry in the currently opened kernel event log file as in the previous test:
```sh
less +F .filemon2/eventlog-000003361.log
event_stamp now_stamp events_new events_cumul repeated i_ino i_generation pid path
## CONT_EPOCH=1568970326.921233648
## MASK=0x7087e0
# LOGROT_END       1568970326.921233648 1579526215.119623204
1579526195.962131308 1579526256.118815926 8000 8000000000008000 660 19113 1285332784 283 /xy
```
1. Unexpected result, dirty event is not written back to kernel event log file before close.

If we bring the configuration file `./filemon2/repeat-timeout-fm2.conf` into play defining a different timeout e.g. by writing into it: `echo 1 >./filemon2/repeat-timeout-fm2.conf` it has no effect, same behaviour as described above.

### Expected and Communicated Behaviour
Latest _before_ the logrotate such delayed events should be written back to the kernel event log before closing the current one. Imagine e.g. SQLite files constantly updated are rarely backed up, in the worst case never more since first creation.

**Comment by schoebel** [comment]
Hi Jürgen,

according to the docs section 2.3, you need to create a small control file extra-logrot-fm2.cmd (or some other *.cmd control) _before_ pushing the trigger.

If you only press the trigger button without prior creation of *.cmd, nothing will happen. This method was negotiated with Andrei some years ago, in order to avoid busy-wait scanning by the kernel.

I have forgotten to mention in the docs that a _combination_ of *.cmd with the trigger is needed. I will publish a doc update soon.
